### PR TITLE
Ensure flush happens and correctly lock connection for a series of unflushed writes

### LINKED ISSUE #160: v1.6.0 causing rabbit connection errors
We just pulled in v1.6.0 on Friday and within 5 mins of normal heavy load we started to see connection errors. Sometimes it got so bad we couldn't get a solid connection for an hour. We backed down to v1.5.0 and making connections were working again.

We are using:
- golang v1.18.8
- Rabbit MQ 3.9

In our client logs we see this error:
```
Channel closed with error - Exception (501) Reason: "short write"
```

In the Rabbit logs we are seeing:
```
0.1072.86>  operation none caused a connection exception frame_error: "type 20, all octets = <<>>: {frame_too_large,1936943471,131064}"
Jan 30 07:31:01 ibm-cloud-databases-prod 2023-01-30T12:31:01.498290249Z stdout F 2023-01-30 12:31:01.496657+00:00 [error] <0.22553.86>  operation none caused a connection exception frame_error: "type 3, first 16 octets = <<31,139,8,0,0,0,0,0,0,255,140,85,201,174,163,74>>: {invalid_frame_end_marker,\n                                                                               222}"
Jan 30 08:06:31 ibm-cloud-databases-prod 2023-01-30T13:06:31.1258836Z stdout F 2023-01-30 13:06:31.090056+00:00 [error] <0.5473.88>  operation none caused a connection exception frame_error: "type 20, all octets = <<>>: {frame_too_large,1936943471,131064}"
Jan 30 08:23:40 ibm-cloud-databases-prod 2023-01-30T13:23:40.184025484Z stdout F 2023-01-30 13:23:40.181798+00:00 [error] <0.17411.117>  operation none caused a connection exception frame_error: "type 26, all octets = <<>>: {frame_too_large,2037148769,131064}"
Jan 30 09:19:15 ibm-cloud-databases-prod 2023-01-30T14:19:14.732511148Z stdout F 2023-01-30 14:19:14.708010+00:00 [error] <0.22659.106>  operation none caused a connection exception frame_error: "type 59, all octets = <<>>: {frame_too_large,2621440,131064}"
```

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #160

cc @fadams

### CODE REVIEW

File: connection.go [hunk 1]
```diff
@@ -468,9 +480,7 @@ func (c *Connection) sendUnflushed(f frame) error {
 		return ErrClosed
 	}
 
-	c.sendM.Lock()
-	err := f.write(c.writer.w)
-	c.sendM.Unlock()
+	err := c.writer.WriteFrameNoFlush(f)
```
Comment (Zerpet) [inline connection.go:483]: Don't you need a lock here to prevent concurrent access to `Connection.writer` here?

Comment (lukebakken) [reply connection.go:483]: No, go up a function call and you'll see that this is only called within a locked section of code.

**Review by Zerpet — APPROVED** [review]
